Add value to owned items if filter is true and fix tests.
gw2efficiency/recipe-calculation pull request #27
Opened 2024-11-07 22:22 UTC by Ecmelt

2024-11-10 22:29 UTC, queicherius requested changes
Looks mostly good, please check the comments and add a test for this change

2024-11-10 22:29 UTC, queicherius commented on src/cheapestTree.ts
> +  valueOwnItems: string = 'false'
I think this makes sense to be `false` (not the string). Let's just use the user's material settings, `BUY | SELL` is overkill for this (we can add it later if requested)

2024-11-10 22:29 UTC, queicherius commented on src/cheapestTree.ts
> +    tree.craftDecisionPrice * 0.85 > tree.buyPrice
I think this is easier to understand flipped and with an explainer comment:

```ts
// If buying the item is less gold than we can get by selling the ingredients (incl. TP tax), we should just buy the item instead
tree.buyPrice < tree.craftDecisionPrice * 0.85
```

(Feel free to reword)

2024-11-10 22:29 UTC, queicherius commented on src/cheapestTree.ts
> +    disableCraftForItemIds(tree, cheaperToBuyItemIds)
Does this not have to be below L33?

2024-11-10 22:29 UTC, queicherius commented on tests/__snapshots__/calculateTreeCraftFlags.spec.ts.snap
> +      "multipleRecipeCount": 1,
This would be easier to review in another PR with just this change.

2024-11-11 20:41 UTC, queicherius requested changes

2024-11-11 20:41 UTC, queicherius commented on src/cheapestTree.ts
> +    disableCraftForItemIds(tree, cheaperToBuyItemIds)
Ah, that makes sense. Could you add a quick oneliner comment above that ("calculateTreeQuantity already checks for craft flags, so we can adjust it here")

2024-11-11 20:41 UTC, queicherius commented on package.json
> +  "version": "3.3.0",
Could you undo this? Else it likely breaks our release tooling

2024-11-12 13:09 UTC, Ecmelt commented
@queicherius the test fails with `Argument of type 'true' is not assignable to parameter of type 'false'.`

2024-11-14 04:18 UTC, queicherius approved these changes

2024-11-14 04:18 UTC, merged